# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box = "centos7"

  config.vm.box_url = "https://f0fff3908f081cb6461b407be80daf97f07ac418.googledrive.com/host/0BwtuV7VyVTSkUG1PM3pCeDJ4dVE/centos7.box"

  config.vm.define "controller" do |controller|
    controller.vm.network :private_network, ip: "10.0.0.11"
    controller.vm.hostname = "controller"
    # Otherwise using VirtualBox
    controller.vm.provider :virtualbox do |vbox|
      # Defaults
      vbox.customize ["modifyvm", :id, "--memory",
        1500]
      vbox.customize ["modifyvm", :id, "--cpus", 1]
  end

end
end
